### ISSUE TITLE
CVEs Related Products missing properties for v1 parity

### ISSUE THREAD

**Issue by kahboom** [guacsec/trustify#975]
In v1 CVE detail page you have the following properties visible for its related products, which are not available now:

- `Version`
- `Dependencies`
- `Supplier`
- `Created on` - unless it's the same as `published`?

See also [this](https://docs.google.com/spreadsheets/d/1mhBd3-UYvSANIXwRPDrCdGplN7cq5rQPJhIywo5mcDY/edit?gid=1088076328#gid=1088076328) spreadsheet for a complete list of properties missing in the current version of the UI.

![Screenshot 2024-11-06 at 2 04 48 PM copy](https://github.com/user-attachments/assets/41ffd4ed-7ba4-4598-9d1c-6d5fd23222ab)

**Comment by ctron** [comment]
I think the following fields are already available:

* Version
* Supplier
* Created on

![image](https://github.com/user-attachments/assets/a72da201-1c30-47b6-89c2-57391d2e944a)

**Comment by kahboom** [comment]
>I think the following fields are already available

thanks @ctron , not sure how I missed that 😅

**Comment by ctron** [comment]
> > I think the following fields are already available
> 
> thanks @ctron , not sure how I missed that 😅

No worries, I am working on the other fields.
